/**
 * Toh Framework Uninstaller — `toh uninstall`
 *
 * The counterpart to `toh install`, written for someone who has no idea what
 * any of these files are. Three rules outrank everything else here:
 *
 *   1. Never delete or corrupt a file the user wrote. When ownership is not
 *      provable, LEAVE the file and say so.
 *   2. Files we share with the user (CLAUDE.md, AGENTS.md, .claude/settings.json,
 *      .agents/hooks.json, ...) are edited SURGICALLY — our marker block or our
 *      hook entry only, every other byte untouched. Our part missing or the file
 *      unreadable => warn and skip, never rewrite.
 *   3. .toh/plan.md, .toh/progress.md and both memory folders are the user's
 *      live work. They are KEPT unless the user explicitly asks for --all,
 *      and even then a copy is saved first.
 *
 * Ownership evidence, strongest first:
 *   a. .toh/manifest.json manifestSchema >= 2 — path + sha256 of every file the
 *      installer actually wrote, plus what a co-owned file looked like BEFORE
 *      the install. Hash match = ours and unmodified; mismatch = the user edited
 *      it, so we keep it.
 *   b. our own markers: <!-- TOH-FRAMEWORK-START/END --> (AGENTS.md),
 *      <TFW-STOP-HOOK> (both hook files), '<!-- generated by toh-framework -->'
 *      (.claude/loop.md), '# Generated by Toh Framework' (.codex/config.toml).
 *   c. known filenames derived from the running package's src/ — used only when
 *      there is no schema-2 manifest (old, missing or corrupt), and reported as
 *      "could not verify".
 *
 * Directories are removed only when they are empty afterwards. The target
 * directory itself is NEVER removed.
 */

import chalk from 'chalk';
import inquirer from 'inquirer';
import fs from 'fs-extra';
import yaml from 'js-yaml';
import crypto from 'crypto';
import os from 'os';
import { fileURLToPath } from 'url';
import { dirname, join, resolve, relative, basename, parse as parsePath } from 'path';
import { generateClaudeMd } from './ide-handlers/claude-code.js';
import { uninstallCodex } from './ide-handlers/codex.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const SRC_DIR = join(__dirname, '..', 'src');

/**
 * How to spell our own commands back to the user. Most people install with
 * `npx toh-framework install` and never get a `toh` on their PATH, so telling
 * them to run `toh uninstall` would print "command not found". Only echo the
 * short form when that is literally how this process was started.
 */
const INVOKED_AS = basename(process.argv[1] || '');
const INVOKED_PATH = (process.argv[1] || '').replace(/\\/g, '/');
// The short name only works when it is actually on the user's PATH — i.e. a
// global install. `npx toh-framework ...` runs the very same bin file out of a
// throwaway cache (/_npx/) or a project's node_modules/.bin, where echoing
// `toh-framework install` back would print "command not found".
const IS_EPHEMERAL_BIN =
  INVOKED_PATH.includes('/_npx/') ||
  INVOKED_PATH.includes('/node_modules/.bin/') ||
  process.env.npm_command === 'exec' ||
  /\bnpm\/[\d.]+ .*\bexec\b/.test(process.env.npm_config_user_agent || '');
const CLI =
  !IS_EPHEMERAL_BIN && (INVOKED_AS === 'toh' || INVOKED_AS === 'toh-framework')
    ? INVOKED_AS
    : 'npx toh-framework';
const CMD_UNINSTALL = `${CLI} uninstall`;
const CMD_INSTALL = `${CLI} install`;

// ------------------------------------------------------------------
// Constants shared with the installer / IDE handlers
// ------------------------------------------------------------------
const TFW_STOP_HOOK_MARKER = '<TFW-STOP-HOOK>';
const TFW_LOOP_MARKER = '<!-- generated by toh-framework -->';
const TOH_BLOCK_START = '<!-- TOH-FRAMEWORK-START -->';
const TOH_BLOCK_END = '<!-- TOH-FRAMEWORK-END -->';
const CODEX_CONFIG_STAMP = '# Generated by Toh Framework';
const ALIAS_SIGNATURE = 'This is a thin alias for `/toh';

const SURFACE_ROOTS = ['.toh', '.claude', '.cursor', '.agents', '.agent', '.codex', '.gemini'];

// The user's live work — never removed without --all.
const LIVE_STATE_FILES = ['.toh/plan.md', '.toh/progress.md'];
const LIVE_STATE_DIRS = ['.toh/memory/', '.claude/memory/'];

// Files we share with the user: each has its own surgical strategy below.
const CO_OWNED = new Set([
  'CLAUDE.md',
  'AGENTS.md',
  '.cursorrules',
  '.claude/settings.json',
  '.claude/loop.md',
  '.agents/hooks.json',
  '.codex/config.toml',
  '.gemini/settings.json',
  '.gemini/GEMINI.md'
]);

const GROUPS = {
  claude: 'The Toh files for Claude Code (.claude/, CLAUDE.md)',
  cursor: 'The Toh files for Cursor (.cursor/)',
  // .agents/ is the shared open standard — Antigravity, Codex, Cursor 2.4 and
  // ZCode all read it, so the label must not name only one of them.
  antigravity: 'The shared Toh agent files (.agents/, .agent/) — Antigravity, Codex, Cursor, ZCode',
  codex: 'The Toh files for Codex / ZCode (AGENTS.md, .codex/)',
  gemini: 'The Toh files for Gemini CLI (.gemini/) — the old setup',
  shared: 'The shared Toh folder (.toh/)',
  user: 'Your own files'
};

function groupOf(rel) {
  if (rel === 'CLAUDE.md' || rel.startsWith('.claude/')) return 'claude';
  if (rel === '.cursorrules' || rel.startsWith('.cursor/')) return 'cursor';
  if (rel.startsWith('.agents/') || rel.startsWith('.agent/')) return 'antigravity';
  if (rel === 'AGENTS.md' || rel.startsWith('.codex/')) return 'codex';
  if (rel.startsWith('.gemini/')) return 'gemini';
  if (rel.startsWith('.toh/')) return 'shared';
  return 'user';
}

// ------------------------------------------------------------------
// Small filesystem helpers (all paths are project-relative, posix style)
// ------------------------------------------------------------------
const sha256 = (buf) => crypto.createHash('sha256').update(buf).digest('hex');

function absOf(targetDir, rel) {
  return join(targetDir, ...rel.split('/'));
}

/**
 * Refuse any path that leaves the project or crosses a symlink.
 * Verified hazard: with .claude/skills symlinked elsewhere, deleting a "known"
 * child path empties a directory outside the project.
 */
async function pathIsSafe(targetDir, rel) {
  const parts = rel.split('/');
  if (parts.some((p) => p === '' || p === '.' || p === '..')) return false;
  let cur = targetDir;
  for (const part of parts) {
    cur = join(cur, part);
    let st;
    try {
      st = await fs.lstat(cur);
    } catch {
      return true; // does not exist -> nothing to traverse, nothing to delete
    }
    if (st.isSymbolicLink()) return false;
  }
  return true;
}

async function isRealFile(targetDir, rel) {
  try {
    const st = await fs.lstat(absOf(targetDir, rel));
    return st.isFile();
  } catch {
    return false;
  }
}

async function isRealDir(targetDir, rel) {
  try {
    const st = await fs.lstat(absOf(targetDir, rel));
    return st.isDirectory();
  } catch {
    return false;
  }
}

async function readText(targetDir, rel) {
  return fs.readFile(absOf(targetDir, rel), 'utf8');
}

async function shaOfFile(targetDir, rel) {
  return sha256(await fs.readFile(absOf(targetDir, rel)));
}

async function listFilesRecursive(dir, prefix = '') {
  const out = [];
  let entries;
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const entry of entries.sort((a, b) => (a.name < b.name ? -1 : 1))) {
    if (entry.isSymbolicLink()) continue;
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) out.push(...(await listFilesRecursive(join(dir, entry.name), rel)));
    else if (entry.isFile()) out.push(rel);
  }
  return out;
}

function plural(n, one, many) {
  return `${n} ${n === 1 ? one : many}`;
}

// ------------------------------------------------------------------
// Catalog: what THIS package installs, by name (fallback ownership evidence)
// ------------------------------------------------------------------
async function buildCatalog(srcDir) {
  const cat = {
    ok: false,
    skillFiles: [],       // relative to <root>/skills
    skillDirs: [],
    agentFiles: [],       // src/agents/*.md (+ README.md)
    agentNames: [],       // frontmatter names AND source filenames
    commandFiles: [],
    templateFiles: [],
    workflowFiles: [],
    geminiCommandFiles: [],
    agentsSkillDirs: []
  };
  if (!(await fs.pathExists(srcDir))) return cat;

  cat.skillFiles = await listFilesRecursive(join(srcDir, 'skills'));
  cat.skillDirs = [...new Set(cat.skillFiles.map((f) => f.split('/')[0]))];

  const agentDir = join(srcDir, 'agents');
  cat.agentFiles = (await listFilesRecursive(agentDir)).filter((f) => !f.includes('/'));
  const names = new Set();
  for (const file of cat.agentFiles) {
    if (!file.endsWith('.md') || file === 'README.md') continue;
    names.add(file); // copy-through fallback writes the source filename
    try {
      const raw = await fs.readFile(join(agentDir, file), 'utf8');
      const fm = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n/);
      const parsed = fm ? yaml.load(fm[1]) : null;
      if (parsed && typeof parsed.name === 'string' && parsed.name.trim()) {
        names.add(`${parsed.name.trim()}.md`);
      }
    } catch {
      // Unparseable source: the filename entry above still covers it.
    }
  }
  cat.agentNames = [...names];

  cat.commandFiles = (await listFilesRecursive(join(srcDir, 'commands'))).filter((f) => !f.includes('/'));
  cat.templateFiles = await listFilesRecursive(join(srcDir, 'templates'));
  cat.workflowFiles = (await listFilesRecursive(join(srcDir, 'antigravity-workflows'))).filter((f) => f.endsWith('.md'));
  cat.geminiCommandFiles = (await listFilesRecursive(join(srcDir, 'gemini-commands'))).filter((f) => f.endsWith('.toml'));

  // .agents/skills = 23 skill wrappers + one command skill per TOML
  const commandSkillNames = cat.geminiCommandFiles.map((f) =>
    f === 'toh.toml' ? 'toh' : `toh-${f.replace(/^toh\//, '').replace(/\.toml$/, '')}`
  );
  cat.agentsSkillDirs = [...new Set([...cat.skillDirs, ...commandSkillNames])];
  // .agents/commands = one native slash command per TOML (ZCode reads these)
  cat.agentsCommandFiles = commandSkillNames.map((n) => `${n}.md`);

  cat.ok = cat.skillDirs.length > 0 && cat.commandFiles.length > 0;
  return cat;
}

/** Every path this package is known to write, by name (existence not checked). */
function derivedPaths(cat) {
  const out = [];
  const add = (p) => out.push(p);

  for (const f of cat.skillFiles) {
    add(`.toh/skills/${f}`);
    add(`.claude/skills/${f}`);
    add(`.gemini/skills/${f}`);
  }
  for (const f of cat.templateFiles) {
    add(`.toh/templates/${f}`);
    add(`.claude/templates/${f}`);
  }
  for (const f of cat.agentFiles) add(`.toh/agents/${f}`);
  for (const f of cat.commandFiles) {
    add(`.toh/commands/${f}`);
    add(`.claude/commands/${f}`);
  }
  for (const n of cat.agentNames) {
    add(`.claude/agents/${n}`);
    add(`.cursor/agents/${n}`);
    add(`.agents/agents/${n}`);
  }
  for (const d of cat.agentsSkillDirs) add(`.agents/skills/${d}/SKILL.md`);
  for (const f of cat.agentsCommandFiles) add(`.agents/commands/${f}`);
  // v2.2: native Codex agents + their ownership manifest
  for (const n of cat.agentNames) add(`.codex/agents/${n.replace(/\.md$/, '')}.toml`);
  add('.codex/toh-framework.json');
  for (const f of cat.workflowFiles) {
    add(`.agents/workflows/${f}`);
    add(`.agent/workflows/${f}`);
  }
  for (const f of cat.geminiCommandFiles) add(`.gemini/commands/${f}`);

  add('.toh/capabilities.json');
  add('.cursor/rules/toh-framework.mdc');
  add('.cursor/rules/toh-agents.mdc');
  add('.agents/rules/toh-framework.md');

  return out;
}

// ------------------------------------------------------------------
// Is there anything of ours here at all?
// ------------------------------------------------------------------
async function detectInstall(targetDir, cat) {
  const probes = [
    '.toh/manifest.json',
    '.toh/capabilities.json',
    '.toh/commands',
    '.toh/agents',
    '.toh/skills',
    '.toh/templates',
    // The live work a default uninstall deliberately KEEPS. Without these
    // probes a follow-up `--all` run would say "I did not find Toh Framework
    // here" and the kept files could never be removed with our own tool.
    '.toh/plan.md',
    '.toh/progress.md',
    '.toh/memory',
    '.cursor/rules/toh-framework.mdc',
    '.agents/rules/toh-framework.md',
    '.gemini/commands/toh.toml',
    '.agent/workflows'
  ];
  for (const p of probes) {
    if ((await isRealFile(targetDir, p)) || (await isRealDir(targetDir, p))) return true;
  }
  // .claude/memory alone counts only when it holds the memory set we seed —
  // a lone user-made .claude/memory/notes.md must never look like an install.
  if (
    (await isRealFile(targetDir, '.claude/memory/summary.md')) &&
    (await isRealFile(targetDir, '.claude/memory/agents-log.md'))
  ) return true;
  for (const d of cat.skillDirs.slice(0, 3)) {
    if (await isRealDir(targetDir, `.claude/skills/${d}`)) return true;
    if (await isRealDir(targetDir, `.agents/skills/${d}`)) return true;
  }
  // Marker-only leftovers (a partially installed tree with nothing else left)
  for (const [rel, marker] of [
    ['AGENTS.md', TOH_BLOCK_START],
    ['.claude/settings.json', TFW_STOP_HOOK_MARKER],
    ['.agents/hooks.json', TFW_STOP_HOOK_MARKER],
    ['.claude/loop.md', TFW_LOOP_MARKER],
    ['.codex/config.toml', CODEX_CONFIG_STAMP]
  ]) {
    if (await isRealFile(targetDir, rel)) {
      try {
        if ((await readText(targetDir, rel)).includes(marker)) return true;
      } catch { /* unreadable -> not evidence */ }
    }
  }
  return false;
}

// ------------------------------------------------------------------
// Planning
// ------------------------------------------------------------------
function newPlan() {
  return {
    removals: [],   // { rel, group, verified }
    edits: [],      // { rel, group, kind, summary, expectedSha, apply-data }
    keeps: [],      // { rel, group, why }        (yours / kept on purpose)
    warnings: [],   // { rel, why }               (left alone, needs a human)
    userWork: [],   // { rel, group }             (deleted only when asked for)
    liveWork: [],   // { rel, group }             (plan/ledger/notes found on disk)
    liveDirs: [],   // 'toh/memory'-style dirs holding live work
    backups: [],    // { rel, to }
    dirs: new Set() // candidate directories to remove when empty
  };
}

/**
 * Promote the user's live work (plan, ledger, notes) onto the delete list.
 * Called for --all, and for a "yes" to the second question in an interactive
 * run — so the choice exists even for someone who never heard of the flag.
 */
function adoptUserWork(plan) {
  plan.keeps = plan.keeps.filter((k) => !k.liveState);
  for (const item of plan.liveWork) {
    if (plan.userWork.some((u) => u.rel === item.rel)) continue;
    plan.userWork.push({ rel: item.rel, group: item.group });
    markDirs(plan, item.rel);
  }
  for (const d of plan.liveDirs) {
    plan.dirs.add(d);
    plan.dirs.add(`${d}/archive`);
  }
}

function markDirs(plan, rel) {
  const parts = rel.split('/');
  parts.pop();
  while (parts.length) {
    plan.dirs.add(parts.join('/'));
    parts.pop();
  }
}

function isLiveState(rel) {
  return LIVE_STATE_FILES.includes(rel) || LIVE_STATE_DIRS.some((d) => rel.startsWith(d));
}

async function buildPlan(ctx) {
  const { targetDir, cat, manifestFiles, hasInventory } = ctx;
  const plan = newPlan();
  const seen = new Set();

  // --- candidate paths: known names + everything the install recorded -------
  const candidates = [];
  for (const rel of derivedPaths(cat)) {
    if (seen.has(rel)) continue;
    seen.add(rel);
    candidates.push({ rel, fromManifest: manifestFiles.has(rel) });
  }
  for (const rel of manifestFiles.keys()) {
    if (seen.has(rel)) continue;
    seen.add(rel);
    candidates.push({ rel, fromManifest: true });
  }
  // Alias command files are data-derived (generated from `aliases:` frontmatter
  // with collision skips) — identify them by their generated body, never by a
  // toh-*.md glob: the user may legitimately author .claude/commands/toh-mine.md.
  if (await isRealDir(targetDir, '.claude/commands')) {
    for (const f of await listFilesRecursive(absOf(targetDir, '.claude/commands'))) {
      const rel = `.claude/commands/${f}`;
      if (seen.has(rel) || !f.endsWith('.md')) continue;
      try {
        if ((await readText(targetDir, rel)).includes(ALIAS_SIGNATURE)) {
          seen.add(rel);
          candidates.push({ rel, fromManifest: manifestFiles.has(rel), aliasFile: true });
        }
      } catch { /* unreadable -> leave it */ }
    }
  }

  // --- classify -------------------------------------------------------------
  for (const cand of candidates.sort((a, b) => (a.rel < b.rel ? -1 : 1))) {
    const { rel } = cand;
    if (CO_OWNED.has(rel)) continue;              // dedicated strategies below
    if (rel === '.toh/manifest.json') continue;   // removed last, on its own
    if (!(await isRealFile(targetDir, rel))) continue;
    if (!(await pathIsSafe(targetDir, rel))) {
      plan.warnings.push({
        rel,
        why: 'this path goes through a shortcut (symlink), so it may point outside your project — I left it alone'
      });
      continue;
    }

    const group = groupOf(rel);

    if (isLiveState(rel)) continue; // handled as one block by planLiveState()

    const record = manifestFiles.get(rel);
    if (record && record.sha256) {
      const actual = await shaOfFile(targetDir, rel);
      if (actual === record.sha256) {
        plan.removals.push({ rel, group, verified: true });
        markDirs(plan, rel);
      } else {
        plan.keeps.push({ rel, group, why: 'you (or a tool) changed this file after it was installed' });
      }
      continue;
    }

    if (hasInventory) {
      // A complete install record exists and does not list this file: it is not
      // ours to delete. Leave it and say where it is.
      plan.warnings.push({ rel, why: 'not in the install record, so I could not confirm it is mine — I left it' });
      continue;
    }

    // No usable install record: fall back to name-scoped removal. The name says
    // the file is ours, but nothing proves the user did not edit it after the
    // install — so a copy goes into the backup folder before it is deleted.
    plan.removals.push({ rel, group, verified: false, backup: true });
    markDirs(plan, rel);
  }

  // --- co-owned files, one strategy each ------------------------------------
  await planClaudeMd(ctx, plan);
  await planMarkerBlock(ctx, plan, 'AGENTS.md');
  await planStopHook(ctx, plan, '.claude/settings.json', 'the Toh "keep going" reminder');
  await planStopHook(ctx, plan, '.agents/hooks.json', 'the Toh "keep going" reminder');
  await planStampedFile(ctx, plan, '.claude/loop.md', TFW_LOOP_MARKER, 'first line');
  await planStampedFile(ctx, plan, '.codex/config.toml', CODEX_CONFIG_STAMP, 'first line');
  await planHashOnlyFile(ctx, plan, '.cursorrules');
  await planHashOnlyFile(ctx, plan, '.gemini/settings.json');
  await planGeminiMd(ctx, plan);

  // --- the user's live work: plan, ledger, both memory folders --------------
  await planLiveState(ctx, plan);

  // Directories the installer created (hint only — emptiness still decides).
  for (const root of SURFACE_ROOTS) plan.dirs.add(root);
  for (const d of ctx.dirsCreated) plan.dirs.add(d);

  return plan;
}

/**
 * .toh/plan.md, .toh/progress.md, .toh/memory/, .claude/memory/ — the user's
 * live work. The installer seeds them; the agents fill them with the project's
 * real plan, ledger and decision history. Kept by default, always.
 */
async function planLiveState(ctx, plan) {
  const { targetDir, includeUserWork } = ctx;

  for (const rel of LIVE_STATE_FILES) {
    if (!(await isRealFile(targetDir, rel))) continue;
    if (!(await pathIsSafe(targetDir, rel))) continue;
    const group = groupOf(rel);
    const label = rel.endsWith('plan.md')
      ? 'your project plan — what the AI is building and what is already ticked off'
      : 'your work log — the record of what has been done so far';
    plan.liveWork.push({ rel, group });
    plan.keeps.push({ rel, group, why: label, liveState: true });
  }

  for (const dir of LIVE_STATE_DIRS) {
    const relDir = dir.replace(/\/$/, '');
    if (!(await isRealDir(targetDir, relDir))) continue;
    const files = await listFilesRecursive(absOf(targetDir, relDir));
    for (const f of files) {
      const rel = `${relDir}/${f}`;
      if (!(await pathIsSafe(targetDir, rel))) continue;
      plan.liveWork.push({ rel, group: groupOf(rel) });
    }
    plan.liveDirs.push(relDir);
    plan.keeps.push({
      rel: `${relDir}/`,
      group: groupOf(relDir),
      liveState: true,
      why: `project notes the AI keeps for you — decisions, architecture, history (${plural(files.length, 'file', 'files')})`
    });
  }

  if (includeUserWork) adoptUserWork(plan);
}

/**
 * CLAUDE.md — the highest-risk file: the installer appends ~455 lines with NO
 * markers at all. The only safe removals are byte-exact ones, which need the
 * manifest (it records the file's sha256 after install and, when we appended to
 * a file the user already had, the exact byte length of their original text).
 * Anything else: leave the file and tell the user where our section starts.
 */
/**
 * Where our own generated text sits inside a CLAUDE.md that has no markers
 * (every install before v2.1 wrote one). Returns { start, end, exact } or null.
 *
 * Two levels of evidence, both anchored on text this package can regenerate:
 *   exact  — our current generated block appears verbatim: provable, no backup
 *            needed.
 *   shaped — the file was written by an older version, so byte-equality fails:
 *            the block still has to start with our H1 line, end with our last
 *            line, and contain most of our section headings. Removal is offered
 *            but flagged unverified, and a copy is always saved first.
 */
function locateClaudeMdBlock(text) {
  for (const lang of ['en', 'th']) {
    const gen = generateClaudeMd(lang);
    const idx = text.indexOf(gen);
    if (idx >= 0) return { start: idx, end: idx + gen.length, exact: true };
  }

  const gen = generateClaudeMd('en');
  const genLines = gen.split('\n').map((l) => l.trim()).filter(Boolean);
  const headings = [...new Set(genLines.filter((l) => /^#{1,3} \S/.test(l)))];
  if (genLines.length === 0 || headings.length < 8) return null;
  const firstLine = genLines[0];
  const lastLine = genLines[genLines.length - 1];

  const startsAtLine = (i) => i === 0 || text[i - 1] === '\n';
  let start = -1;
  for (let i = text.indexOf(firstLine); i >= 0; i = text.indexOf(firstLine, i + 1)) {
    if (startsAtLine(i)) { start = i; break; }
  }
  if (start < 0) return null;

  const endAnchor = text.lastIndexOf(lastLine);
  if (endAnchor <= start) return null;
  let end = endAnchor + lastLine.length;
  if (text[end] === '\r') end += 1;
  if (text[end] === '\n') end += 1;

  const block = text.slice(start, end);
  const found = headings.filter((h) => block.includes(h)).length;
  if (found / headings.length < 0.6) return null;

  return { start, end, exact: false };
}

async function planClaudeMd(ctx, plan) {
  const { targetDir, manifestFiles } = ctx;
  const rel = 'CLAUDE.md';
  if (!(await isRealFile(targetDir, rel))) return;
  if (!(await pathIsSafe(targetDir, rel))) {
    plan.warnings.push({ rel, why: 'this path is a shortcut (symlink) — I left it alone' });
    return;
  }

  const buf = await fs.readFile(absOf(targetDir, rel));
  const sha = sha256(buf);
  const record = manifestFiles.get(rel);
  const mentionsUs = buf.includes('Toh Framework');

  // Installed by v2.1 or later: our section is delimited, so the generic
  // marker-block strategy lifts out exactly our part and nothing else.
  const asText = buf.toString('utf8');
  if (asText.includes(TOH_BLOCK_START) || asText.includes(TOH_BLOCK_END)) {
    await planMarkerBlock(ctx, plan, rel);
    return;
  }

  if (record && record.sha256 === sha) {
    if (!record.preexisted) {
      plan.edits.push({
        rel,
        group: 'claude',
        kind: 'delete',
        expectedSha: sha,
        summary: 'delete it — the whole file was written by Toh Framework'
      });
      markDirs(plan, rel);
      return;
    }
    if (typeof record.preexistedBytes === 'number' && record.preexistedSha256) {
      const prefix = buf.subarray(0, record.preexistedBytes);
      if (prefix.length === record.preexistedBytes && sha256(prefix) === record.preexistedSha256) {
        plan.edits.push({
          rel,
          group: 'claude',
          kind: 'truncate',
          bytes: record.preexistedBytes,
          expectedSha: sha,
          summary: 'take out the Toh section and put your own CLAUDE.md back exactly as it was'
        });
        return;
      }
    }
  }

  // No markers and no matching record — an older install, or the file was
  // edited since. Recognise our own text instead of asking the user to do it.
  const located = mentionsUs ? locateClaudeMdBlock(asText) : null;
  if (located) {
    const before = asText.slice(0, located.start);
    const after = asText.slice(located.end);
    const backup = !located.exact;
    if (before.trim() === '' && after.trim() === '') {
      plan.edits.push({
        rel,
        group: 'claude',
        kind: 'delete',
        expectedSha: sha,
        backup,
        summary: 'delete it — every line in it was written by Toh Framework'
      });
      markDirs(plan, rel);
      return;
    }
    let out = before.replace(/\n\n$/, '') + after;
    if (before.trim() === '') out = out.replace(/^\n+/, '');
    plan.edits.push({
      rel,
      group: 'claude',
      kind: 'write',
      content: out,
      expectedSha: sha,
      backup,
      summary: 'take out the Toh Framework section — everything you wrote in this file stays'
    });
    return;
  }

  if (mentionsUs) {
    const idx = asText.indexOf('# Toh Framework');
    const where = idx >= 0
      ? ` If you want to check, the words "# Toh Framework" appear at line ${asText.slice(0, idx).split('\n').length}.`
      : '';
    const because = record
      ? 'it no longer matches what was installed, so it has been edited since'
      : 'my install record does not list this file';
    plan.warnings.push({
      rel,
      why:
        'this file mentions Toh Framework, but none of it matches the text I write, and ' +
        `${because} — so I could not tell which part (if any) is mine, and I left the file exactly as it is.` +
        `${where} Read it yourself and delete anything of mine you do not want.`
    });
  } else {
    plan.keeps.push({ rel, group: 'claude', why: 'nothing of ours is in it' });
  }
}

/** AGENTS.md — properly delimited, so this works with or without a manifest. */
async function planMarkerBlock(ctx, plan, rel) {
  const { targetDir, manifestFiles } = ctx;
  if (!(await isRealFile(targetDir, rel))) return;
  if (!(await pathIsSafe(targetDir, rel))) {
    plan.warnings.push({ rel, why: 'this path is a shortcut (symlink) — I left it alone' });
    return;
  }

  let text;
  try {
    text = await readText(targetDir, rel);
  } catch (err) {
    plan.warnings.push({ rel, why: `I could not read it (${err.message}) — I left it alone` });
    return;
  }

  const starts = text.split(TOH_BLOCK_START).length - 1;
  const ends = text.split(TOH_BLOCK_END).length - 1;
  if (starts === 0 && ends === 0) {
    plan.keeps.push({ rel, group: groupOf(rel), why: 'nothing of ours is in it' });
    return;
  }
  if (starts !== 1 || ends !== 1) {
    plan.warnings.push({
      rel,
      why: `I found ${starts} start and ${ends} end markers instead of one of each, so I could not tell exactly which part is mine — I left the file alone`
    });
    return;
  }

  const start = text.indexOf(TOH_BLOCK_START);
  const end = text.indexOf(TOH_BLOCK_END, start);
  if (end < 0) {
    plan.warnings.push({ rel, why: 'the end marker comes before the start marker — I left the file alone' });
    return;
  }

  // Lazy, first-START to first-following-END. (The installer's own regex is
  // greedy; copying it would eat user text between two quoted markers.)
  const head = text.slice(0, start).replace(/\n\n$/, '');
  const tail = text.slice(end + TOH_BLOCK_END.length);
  let out = head + tail;
  if (head === '') out = out.replace(/^\n+/, '');

  const record = manifestFiles.get(rel);
  const sha = await shaOfFile(targetDir, rel);

  // Byte-exact restore when our block ends the file and nothing changed since.
  if (
    record &&
    record.sha256 === sha &&
    record.preexisted &&
    typeof record.preexistedBytes === 'number' &&
    record.preexistedSha256 &&
    tail.trim() === ''
  ) {
    const buf = await fs.readFile(absOf(targetDir, rel));
    const prefix = buf.subarray(0, record.preexistedBytes);
    if (prefix.length === record.preexistedBytes && sha256(prefix) === record.preexistedSha256) {
      plan.edits.push({
        rel,
        group: groupOf(rel),
        kind: 'truncate',
        bytes: record.preexistedBytes,
        expectedSha: sha,
        summary: 'take out the Toh section and put your own file back exactly as it was'
      });
      return;
    }
  }

  if (out.trim() === '') {
    plan.edits.push({
      rel,
      group: groupOf(rel),
      kind: 'delete',
      expectedSha: sha,
      summary: 'delete it — it contains nothing but the Toh section'
    });
    markDirs(plan, rel);
    return;
  }

  plan.edits.push({
    rel,
    group: groupOf(rel),
    kind: 'write',
    content: out,
    expectedSha: sha,
    summary: 'take out only the Toh section between its markers — everything you wrote stays'
  });
}

/** .claude/settings.json + .agents/hooks.json — remove ONLY our Stop entry. */
async function planStopHook(ctx, plan, rel, label) {
  const { targetDir, manifestFiles } = ctx;
  if (!(await isRealFile(targetDir, rel))) return;
  if (!(await pathIsSafe(targetDir, rel))) {
    plan.warnings.push({ rel, why: 'this path is a shortcut (symlink) — I left it alone' });
    return;
  }

  let raw;
  try {
    raw = await readText(targetDir, rel);
  } catch (err) {
    plan.warnings.push({ rel, why: `I could not read it (${err.message}) — I left it alone` });
    return;
  }
  if (!raw.includes(TFW_STOP_HOOK_MARKER)) {
    plan.keeps.push({ rel, group: groupOf(rel), why: 'nothing of ours is in it' });
    return;
  }

  let obj;
  try {
    obj = JSON.parse(raw);
  } catch (err) {
    plan.warnings.push({
      rel,
      why: `this file is not valid JSON (${err.message}), so editing it safely is impossible — I left it alone`
    });
    return;
  }
  if (obj === null || typeof obj !== 'object' || Array.isArray(obj)) {
    plan.warnings.push({ rel, why: 'this file does not look like the settings file I expected — I left it alone' });
    return;
  }

  const hooks = obj.hooks;
  const stop = hooks && typeof hooks === 'object' && !Array.isArray(hooks) ? hooks.Stop : undefined;
  if (!Array.isArray(stop)) {
    plan.warnings.push({ rel, why: 'the Toh reminder is not where I expected it — I left this file alone' });
    return;
  }

  const kept = stop.filter((entry) => {
    try {
      return !JSON.stringify(entry === undefined ? null : entry).includes(TFW_STOP_HOOK_MARKER);
    } catch {
      return true; // unserializable -> not ours -> keep
    }
  });
  const removed = stop.length - kept.length;
  if (removed === 0) {
    plan.keeps.push({ rel, group: groupOf(rel), why: 'nothing of ours is in it' });
    return;
  }

  if (kept.length > 0) hooks.Stop = kept;
  else delete hooks.Stop;
  if (Object.keys(hooks).length === 0) delete obj.hooks;

  // Whole-file deletion needs the file to hold nothing but our hook. When the
  // install record knows the file, it decides; with no record at all, an empty
  // leftover object proves the point on its own — the user cannot have authored
  // a settings file whose entire content was our marker.
  const record = manifestFiles.get(rel);
  const weCreatedIt = record ? !record.preexisted : true;
  const sha = await shaOfFile(targetDir, rel);

  if (Object.keys(obj).length === 0 && weCreatedIt) {
    plan.edits.push({
      rel,
      group: groupOf(rel),
      kind: 'delete',
      expectedSha: sha,
      summary: `delete it — it only ever held ${label}`
    });
    markDirs(plan, rel);
    return;
  }

  const othersNote = kept.length > 0
    ? `, keeping ${plural(kept.length, 'other setting of yours', 'other settings of yours')}`
    : '';
  plan.edits.push({
    rel,
    group: groupOf(rel),
    kind: 'write',
    content: `${JSON.stringify(obj, null, 2)}\n`,
    expectedSha: sha,
    summary: `remove ${label}${othersNote} — everything else in this file stays`
  });
}

/** Files carrying a first-line generator stamp (.claude/loop.md, .codex/config.toml). */
async function planStampedFile(ctx, plan, rel, stamp, whereLabel) {
  const { targetDir } = ctx;
  if (!(await isRealFile(targetDir, rel))) return;
  if (!(await pathIsSafe(targetDir, rel))) {
    plan.warnings.push({ rel, why: 'this path is a shortcut (symlink) — I left it alone' });
    return;
  }

  let text;
  try {
    text = await readText(targetDir, rel);
  } catch (err) {
    plan.warnings.push({ rel, why: `I could not read it (${err.message}) — I left it alone` });
    return;
  }
  const firstLine = text.split(/\r?\n/, 1)[0] || '';
  if (firstLine.includes(stamp)) {
    plan.removals.push({ rel, group: groupOf(rel), verified: true });
    markDirs(plan, rel);
  } else {
    plan.warnings.push({
      rel,
      why: `this file does not carry the Toh stamp on its ${whereLabel}, so it looks like yours — I left it`
    });
  }
}

/**
 * Files with no marker at all that the installer OVERWRITES (.cursorrules,
 * .gemini/settings.json). The only honest ownership test is "the bytes are
 * exactly what we wrote", which needs the manifest.
 */
async function planHashOnlyFile(ctx, plan, rel) {
  const { targetDir, manifestFiles } = ctx;
  if (!(await isRealFile(targetDir, rel))) return;
  if (!(await pathIsSafe(targetDir, rel))) {
    plan.warnings.push({ rel, why: 'this path is a shortcut (symlink) — I left it alone' });
    return;
  }

  const record = manifestFiles.get(rel);
  const sha = await shaOfFile(targetDir, rel);
  if (record && record.sha256 === sha) {
    plan.removals.push({
      rel,
      group: groupOf(rel),
      verified: true,
      note: record.preexisted
        ? 'heads-up: you had your own version of this file before Toh Framework was installed, and the installer replaced it — the original cannot be brought back'
        : undefined
    });
    markDirs(plan, rel);
    return;
  }

  let mentionsUs = false;
  try {
    mentionsUs = (await readText(targetDir, rel)).includes('Toh Framework');
  } catch { /* unreadable */ }
  if (mentionsUs || record) {
    plan.warnings.push({
      rel,
      why: 'I could not confirm this file is exactly the one Toh Framework wrote (it has no markers), so I left it — check it and delete it yourself if you want it gone'
    });
  }
}

/** .gemini/GEMINI.md — ours-exclusive, but only if the rest of .gemini/ is ours. */
async function planGeminiMd(ctx, plan) {
  const { targetDir, manifestFiles, hasInventory } = ctx;
  const rel = '.gemini/GEMINI.md';
  if (!(await isRealFile(targetDir, rel))) return;
  if (!(await pathIsSafe(targetDir, rel))) {
    plan.warnings.push({ rel, why: 'this path is a shortcut (symlink) — I left it alone' });
    return;
  }

  const record = manifestFiles.get(rel);
  const sha = await shaOfFile(targetDir, rel);
  if (record && record.sha256 === sha) {
    plan.removals.push({ rel, group: 'gemini', verified: true });
    markDirs(plan, rel);
    return;
  }
  if (hasInventory) {
    plan.warnings.push({ rel, why: 'not in the install record or changed since — I left it' });
    return;
  }
  const text = await readText(targetDir, rel).catch(() => '');
  const geminiIsOurs = await isRealFile(targetDir, '.gemini/commands/toh.toml');
  if (text.includes('Toh Framework') && geminiIsOurs) {
    plan.removals.push({ rel, group: 'gemini', verified: false, backup: true });
    markDirs(plan, rel);
  } else {
    plan.warnings.push({ rel, why: 'I could not confirm this file is mine — I left it' });
  }
}

// ------------------------------------------------------------------
// Preview (plain language)
// ------------------------------------------------------------------
function printPlan(plan, ctx) {
  const { targetDir, hasInventory, verbose } = ctx;

  console.log(chalk.bold(`\nHere is what "remove Toh Framework" means for this folder:`));
  console.log(chalk.gray(`  ${targetDir}\n`));

  // Grouped removals
  const byGroup = new Map();
  for (const item of plan.removals) {
    if (!byGroup.has(item.group)) byGroup.set(item.group, []);
    byGroup.get(item.group).push(item);
  }
  const wholeFileDeletes = plan.edits.filter((e) => e.kind === 'delete');
  const surgicalEdits = plan.edits.filter((e) => e.kind !== 'delete');

  if (byGroup.size === 0 && plan.edits.length === 0 && plan.userWork.length === 0) {
    console.log(chalk.yellow('  There is nothing of mine left to remove.\n'));
  } else if (byGroup.size > 0 || wholeFileDeletes.length > 0) {
    console.log(chalk.bold('I will REMOVE the Toh Framework files:'));
    for (const key of Object.keys(GROUPS)) {
      const items = byGroup.get(key);
      if (!items || items.length === 0) continue;
      const unverified = items.filter((i) => !i.verified).length;
      const suffix = unverified > 0
        ? chalk.gray(`  (matched by name — a copy of each goes to ${ctx.backupDirName}/ first)`)
        : '';
      console.log(`  • ${GROUPS[key]} — ${chalk.cyan(plural(items.length, 'file', 'files'))}${suffix}`);
      if (verbose) for (const i of items) console.log(chalk.gray(`      ${i.rel}`));
    }
    for (const e of wholeFileDeletes) {
      console.log(`  • ${chalk.cyan(e.rel)} — ${e.summary.replace(/^delete it — /, '')}`);
    }
    const notes = plan.removals.filter((i) => i.note);
    for (const n of notes) console.log(chalk.yellow(`    ! ${n.rel}: ${n.note}`));
    console.log('');
  }

  if (surgicalEdits.length > 0) {
    console.log(chalk.bold('I will OPEN these files and take out only the Toh part:'));
    for (const e of surgicalEdits) console.log(`  • ${chalk.cyan(e.rel)} — ${e.summary}`);
    console.log(chalk.gray('    Everything else in those files is left byte-for-byte as it is.\n'));
  }

  if (plan.userWork.length > 0) {
    console.log(chalk.bold.red('I will ALSO DELETE your own project work:'));
    for (const w of plan.userWork) console.log(`  • ${chalk.red(w.rel)}`);
    console.log(chalk.yellow(`    A copy is saved to ${ctx.backupDirName}/ first, so you can still get it back.\n`));
  }

  if (plan.keeps.length > 0) {
    console.log(chalk.bold('I will KEEP these — they are yours:'));
    for (const k of plan.keeps) console.log(`  • ${chalk.green(k.rel)} — ${k.why}`);
    if (plan.liveWork.length > 0 && plan.userWork.length === 0) {
      console.log(chalk.gray(
        `    Your plan and your notes stay exactly where they are.\n` +
        `    Want a completely empty folder instead? Run:  ${CMD_UNINSTALL} --all` +
        `  (${plural(plan.liveWork.length, 'file', 'files')}, copied to ${ctx.backupDirName}/ first)`
      ));
    }
    console.log('');
  }

  if (plan.warnings.length > 0) {
    console.log(chalk.bold.yellow('I will NOT touch these — I could not be sure they are mine:'));
    for (const w of plan.warnings) console.log(`  • ${chalk.yellow(w.rel)} — ${w.why}`);
    console.log('');
  }

  if (!hasInventory) {
    console.log(chalk.gray(
      '  Note: this project has no complete install record (it was installed by an older version,\n' +
      '  or the record was deleted), so I matched files by their names instead. Every file removed\n' +
      `  that way is copied into ${ctx.backupDirName}/ first, and anything that is not clearly mine\n` +
      '  is left alone.\n'
    ));
  }
}

// ------------------------------------------------------------------
// Execution
// ------------------------------------------------------------------
async function applyPlan(plan, ctx) {
  const { targetDir } = ctx;
  const result = {
    removed: [], edited: [], failed: [], skipped: [], removedDirs: [],
    backups: [], workBackups: []
  };

  /**
   * Copy a file into .toh-uninstall-backup/ before it is touched. Used for the
   * user's own work AND for every file we could only match by name: without an
   * install record there is no way to know whether the user edited it, and an
   * edit the user cannot get back is the one outcome this command must never
   * produce. A failed backup cancels that file's deletion.
   */
  const backup = async (item, bucket) => {
    try {
      const dest = join(absOf(targetDir, ctx.backupDirName), ...item.rel.split('/'));
      await fs.ensureDir(dirname(dest));
      await fs.copy(absOf(targetDir, item.rel), dest, { overwrite: true, errorOnExist: false });
      bucket.push(item.rel);
      return true;
    } catch (err) {
      result.failed.push({
        rel: item.rel,
        why: `could not save a backup copy (${err.message}) — so I did not touch it`
      });
      item.skip = true;
      return false;
    }
  };

  // 1. Back up the user's live work before deleting it.
  for (const item of plan.userWork) await backup(item, result.workBackups);

  // 2. Back up every unverified (name-matched) file and edit.
  for (const item of plan.removals) {
    if (!item.backup) continue;
    if (!(await isRealFile(targetDir, item.rel))) continue;
    await backup(item, result.backups);
  }
  for (const edit of plan.edits) {
    if (!edit.backup) continue;
    if (!(await isRealFile(targetDir, edit.rel))) continue;
    await backup(edit, result.backups);
  }

  // 3. Plain file removals (+ the user work the backup step protected).
  for (const item of [...plan.removals.filter((i) => !i.skip), ...plan.userWork.filter((i) => !i.skip)]) {
    if (!(await pathIsSafe(targetDir, item.rel))) {
      result.skipped.push({ rel: item.rel, why: 'the path became a shortcut (symlink) — skipped for safety' });
      continue;
    }
    if (!(await isRealFile(targetDir, item.rel))) continue; // already gone: idempotent
    try {
      await fs.unlink(absOf(targetDir, item.rel));
      result.removed.push(item.rel);
    } catch (err) {
      result.failed.push({ rel: item.rel, why: err.message });
    }
  }

  // 4. Surgical edits — re-verified against what we previewed.
  for (const edit of plan.edits) {
    if (edit.skip) continue; // its backup failed: leave the file exactly as it is
    if (!(await pathIsSafe(targetDir, edit.rel))) {
      result.skipped.push({ rel: edit.rel, why: 'the path became a shortcut (symlink) — skipped for safety' });
      continue;
    }
    if (!(await isRealFile(targetDir, edit.rel))) continue;
    try {
      const nowSha = await shaOfFile(targetDir, edit.rel);
      if (edit.expectedSha && nowSha !== edit.expectedSha) {
        result.skipped.push({ rel: edit.rel, why: 'the file changed while I was asking you — I left it alone' });
        continue;
      }
      const abs = absOf(targetDir, edit.rel);
      if (edit.kind === 'delete') {
        await fs.unlink(abs);
        result.removed.push(edit.rel);
      } else if (edit.kind === 'truncate') {
        await fs.truncate(abs, edit.bytes);
        result.edited.push({ rel: edit.rel, summary: edit.summary });
      } else {
        await fs.writeFile(abs, edit.content);
        result.edited.push({ rel: edit.rel, summary: edit.summary });
      }
    } catch (err) {
      result.failed.push({ rel: edit.rel, why: err.message });
    }
  }

  // 5. Directories: deepest first, only when empty.
  const dirs = [...plan.dirs].sort((a, b) => b.split('/').length - a.split('/').length || (a < b ? 1 : -1));
  for (const rel of dirs) {
    if (!rel || rel === '.') continue;
    if (!(await pathIsSafe(targetDir, rel))) continue;
    if (!(await isRealDir(targetDir, rel))) continue;
    try {
      const entries = await fs.readdir(absOf(targetDir, rel));
      if (entries.length === 0) {
        await fs.rmdir(absOf(targetDir, rel));
        result.removedDirs.push(rel);
      }
    } catch (err) {
      result.failed.push({ rel, why: `could not tidy up the folder (${err.message})` });
    }
  }

  return result;
}

/**
 * The manifest goes LAST. If anything of ours is still on disk (a file you
 * edited, a failure), we keep a trimmed record so a second `toh uninstall` can
 * finish the job instead of guessing.
 */
async function finalizeManifest(ctx, plan, result) {
  const { targetDir } = ctx;
  const rel = '.toh/manifest.json';
  if (!(await isRealFile(targetDir, rel))) return null;

  const leftovers = [
    ...plan.keeps.filter((k) => !isLiveState(k.rel) && !k.rel.endsWith('/')).map((k) => k.rel),
    ...plan.warnings.map((w) => w.rel),
    ...result.failed.map((f) => f.rel),
    ...result.skipped.map((s) => s.rel)
  ];
  const stillOurs = [];
  for (const p of new Set(leftovers)) {
    if (ctx.manifestFiles.has(p) && (await isRealFile(targetDir, p))) stillOurs.push(p);
  }

  if (stillOurs.length === 0 && result.failed.length === 0) {
    try {
      await fs.unlink(absOf(targetDir, rel));
      result.removed.push(rel);
    } catch (err) {
      result.failed.push({ rel, why: err.message });
    }
    // .toh may now be empty (nothing kept) — try one last tidy-up.
    for (const d of ['.toh/memory/archive', '.toh/memory', '.toh']) {
      if (!(await isRealDir(targetDir, d))) continue;
      try {
        if ((await fs.readdir(absOf(targetDir, d))).length === 0) {
          await fs.rmdir(absOf(targetDir, d));
          result.removedDirs.push(d);
        }
      } catch { /* leave it */ }
    }
    return null;
  }

  try {
    const manifest = await fs.readJson(absOf(targetDir, rel));
    manifest.files = (manifest.files || []).filter((f) => stillOurs.includes(f.path));
    manifest.uninstallPartial = true;
    manifest.uninstalledAt = new Date().toISOString();
    await fs.writeJson(absOf(targetDir, rel), manifest, { spaces: 2 });
    return stillOurs.length;
  } catch {
    return stillOurs.length;
  }
}

// ------------------------------------------------------------------
// Final report
// ------------------------------------------------------------------
async function printReport(ctx, plan, result, manifestKept) {
  const { targetDir } = ctx;

  console.log(chalk.bold('\n──────────────────────────────────────────────────────────────'));
  console.log(chalk.bold.green('Done. Here is exactly what happened:\n'));

  if (result.removed.length > 0) {
    console.log(`  ${chalk.green('✔')} Removed ${chalk.cyan(plural(result.removed.length, 'Toh file', 'Toh files'))}` +
      (result.removedDirs.length ? ` and ${plural(result.removedDirs.length, 'empty folder', 'empty folders')}` : '') + '.');
  } else {
    console.log(`  ${chalk.green('✔')} There were no Toh files left to remove.`);
  }
  for (const e of result.edited) {
    console.log(`  ${chalk.green('✔')} ${chalk.cyan(e.rel)} — ${e.summary}`);
  }
  if (result.workBackups.length > 0) {
    console.log(`  ${chalk.green('✔')} Saved a copy of your plan and notes in ${chalk.cyan(ctx.backupDirName + '/')} before deleting them.`);
  }
  if (result.backups.length > 0) {
    console.log(`  ${chalk.green('✔')} Saved a copy of ${chalk.cyan(plural(result.backups.length, 'file', 'files'))} I could only match by name in ` +
      `${chalk.cyan(ctx.backupDirName + '/')} before removing them, in case you had changed any of them.`);
  }

  if (plan.keeps.length > 0) {
    console.log(chalk.bold('\n  Kept for you (untouched):'));
    for (const k of plan.keeps) console.log(`    • ${chalk.green(k.rel)} — ${k.why}`);
    if (plan.liveWork.length > 0 && plan.userWork.length === 0) {
      console.log(chalk.gray(
        `    Your plan and your notes are still here. To remove those too — a copy is saved first — run:\n` +
        `      ${CMD_UNINSTALL} --all`
      ));
    }
  }

  const leftAlone = [...plan.warnings, ...result.skipped.map((s) => ({ rel: s.rel, why: s.why }))];
  if (leftAlone.length > 0) {
    console.log(chalk.bold.yellow('\n  Left alone on purpose (please look at these yourself):'));
    for (const w of leftAlone) console.log(`    • ${chalk.yellow(w.rel)} — ${w.why}`);
  }

  // Folders we kept because something that is not ours is still inside them —
  // name the actual files, not just the folder, so nothing is a mystery.
  const alreadyMentioned = new Set([
    '.toh/manifest.json',
    ...plan.keeps.map((k) => k.rel.replace(/\/$/, '')),
    ...plan.warnings.map((w) => w.rel),
    ...result.edited.map((e) => e.rel),
    ...result.skipped.map((s) => s.rel),
    ...result.failed.map((f) => f.rel)
  ]);
  const leftoverFiles = [];
  const keptFolders = [];
  for (const root of SURFACE_ROOTS) {
    if (!(await isRealDir(targetDir, root))) continue;
    keptFolders.push(root);
    for (const f of await listFilesRecursive(absOf(targetDir, root))) {
      const rel = `${root}/${f}`;
      if (isLiveState(rel)) continue;
      if (alreadyMentioned.has(rel)) continue;
      if (LIVE_STATE_DIRS.some((d) => rel.startsWith(d))) continue;
      leftoverFiles.push(rel);
    }
  }
  if (leftoverFiles.length > 0) {
    console.log(chalk.bold('\n  Files of yours I found inside my folders — kept, and here is where they are:'));
    for (const rel of leftoverFiles.slice(0, 12)) console.log(`    • ${chalk.green(rel)}`);
    if (leftoverFiles.length > 12) console.log(chalk.gray(`    ...and ${leftoverFiles.length - 12} more`));
  }
  if (keptFolders.length > 0) {
    console.log(chalk.gray(
      `\n  Folders kept because they are not empty: ${keptFolders.map((f) => `${f}/`).join(', ')}`
    ));
  }

  if (result.failed.length > 0) {
    console.log(chalk.bold.red('\n  These did NOT work:'));
    for (const f of result.failed) console.log(`    • ${chalk.red(f.rel)} — ${f.why}`);
    console.log(chalk.red(`\n  Nothing else was changed. Fix the problem above and run \`${CMD_UNINSTALL}\` again.`));
  }

  if (manifestKept) {
    console.log(chalk.gray(
      `\n  I kept .toh/manifest.json (the install record) because ${plural(manifestKept, 'file is', 'files are')} still there. ` +
      `Running \`${CMD_UNINSTALL}\` again is safe and will pick up where this left off.`
    ));
  }

  if (result.backups.length > 0 || result.workBackups.length > 0) {
    console.log(chalk.gray(
      `\n  The copies are in ${ctx.backupDirName}/. Once you are happy with the result you can delete that folder.`
    ));
  }

  console.log(chalk.bold('\n  Want it back? Run:'));
  console.log(`    ${chalk.cyan(CMD_INSTALL)}`);
  console.log(chalk.gray(
    result.workBackups.length > 0
      ? `    (your plan and notes are in ${ctx.backupDirName}/ — copy them back into .toh/ if you reinstall)\n`
      : '    (your plan and notes are still here, so it picks up where you left off)\n'
  ));
}

// ------------------------------------------------------------------
// Entry point
// ------------------------------------------------------------------
export async function uninstall(options = {}) {
  const targetDir = resolve(options.target || process.cwd());
  const dryRun = !!options.dryRun;
  const assumeYes = !!options.yes;
  const includeUserWork = !!options.all;
  const verbose = !!options.verbose;
  const requestedIdes = options.ide
    ? String(options.ide).split(',').map((ide) => ide.trim().toLowerCase()).filter(Boolean)
    : null;

  console.log(chalk.cyan(`\n🧹 Removing Toh Framework from:\n   ${targetDir}\n`));

  // --- refuse dangerous roots ----------------------------------------------
  if (!fs.existsSync(targetDir)) {
    console.log(chalk.yellow(`That folder does not exist, so there is nothing to remove.\n`));
    return 0;
  }
  const isRoot = targetDir === parsePath(targetDir).root;
  const isHome = resolve(os.homedir()) === targetDir;
  if (isRoot || isHome) {
    console.log(chalk.red(
      `I will not remove anything from ${isHome ? 'your home folder' : 'the top of your disk'}.\n` +
      `Toh Framework is installed per project — open your project folder and run it there,\n` +
      `or point at it with:  ${CMD_UNINSTALL} -t /path/to/your/project\n`
    ));
    return 1;
  }

  // --- per-IDE removal (v2.2: Codex only) ------------------------------------
  // `--ide codex` removes just the native agent files this installer wrote
  // (hash-verified) plus their manifest. AGENTS.md and .codex/config.toml are
  // shared surfaces (ZCode reads AGENTS.md too) and stay — run without --ide
  // for the complete, previewed removal.
  if (requestedIdes) {
    const isCodex = (ide) => ide === 'codex' || ide === 'codex-cli';
    if (!requestedIdes.every(isCodex)) {
      const unsupported = requestedIdes.filter((ide) => !isCodex(ide));
      console.log(chalk.yellow(
        `Per-IDE removal currently supports Codex only (got: ${unsupported.join(', ')}).\n` +
        `Run without --ide for a full uninstall, or use --ide codex.\n`
      ));
      return 1;
    }
    // Same manners as the full path: preview first, then one question.
    const preview = await uninstallCodex(targetDir, { dryRun: true });
    const keptNote = preview.keptAgents.length
      ? ` ${plural(preview.keptAgents.length, 'file', 'files')} you edited will stay: ${preview.keptAgents.join(', ')}.`
      : '';
    const staysNote = 'AGENTS.md, .codex/config.toml and .toh/ stay (shared surfaces — run without --ide to remove everything).';
    if (preview.removedAgents.length === 0) {
      console.log(chalk.yellow(`No Toh-written native agent files found in .codex/agents/ — nothing to remove.${keptNote}\n${staysNote}\n`));
      return 0;
    }
    console.log(chalk.white(
      `I will remove ${plural(preview.removedAgents.length, 'native agent file', 'native agent files')} from .codex/agents/ ` +
      `(${preview.removedAgents.join(', ')}) plus .codex/toh-framework.json.${keptNote}\n${staysNote}\n`
    ));
    if (dryRun) {
      console.log(chalk.gray('This was a preview (--dry-run). Nothing was deleted or changed.\n'));
      return 0;
    }
    if (!assumeYes) {
      let go = false;
      try {
        ({ go } = await inquirer.prompt([{ type: 'confirm', name: 'go', message: 'Go ahead?', default: false }]));
      } catch {
        console.log(chalk.yellow('\nI could not read your answer, so I stopped and changed nothing.\n'));
        return 1;
      }
      if (!go) {
        console.log(chalk.yellow('\nStopped. Nothing was changed.\n'));
        return 0;
      }
    }
    const result = await uninstallCodex(targetDir, { dryRun: false, backup: options.backup !== false });
    console.log(chalk.green(
      `Codex: removed ${plural(result.removedAgents.length, 'native agent file', 'native agent files')} from .codex/agents/.` +
      (result.backupPath ? ` A copy was saved to ${relative(targetDir, result.backupPath)}/ first.` : '') + '\n'
    ));
    return 0;
  }

  // --- gather evidence ------------------------------------------------------
  const cat = await buildCatalog(SRC_DIR);
  if (!(await detectInstall(targetDir, cat))) {
    console.log(chalk.green('I did not find Toh Framework in this folder, so I changed nothing.\n'));
    console.log(chalk.gray(`  (If your project is somewhere else, run:  ${CMD_UNINSTALL} -t /path/to/your/project)\n`));
    return 0;
  }

  let manifest = null;
  let manifestBroken = false;
  if (await isRealFile(targetDir, '.toh/manifest.json')) {
    try {
      manifest = await fs.readJson(absOf(targetDir, '.toh/manifest.json'));
    } catch {
      manifestBroken = true;
    }
  }

  const manifestFiles = new Map();
  let hasInventory = false;
  if (manifest && Number(manifest.manifestSchema) >= 2 && Array.isArray(manifest.files)) {
    for (const f of manifest.files) {
      if (f && typeof f.path === 'string' && typeof f.sha256 === 'string') manifestFiles.set(f.path, f);
    }
    hasInventory = manifestFiles.size > 0 && !manifest.inventoryTruncated;
  }

  // A record that lists only a handful of the files that are plainly on disk is
  // worse than no record: it would make us declare our own files "not mine" and
  // stop halfway, leaving a broken half-install (settings edited, files intact).
  // Measure it against reality and fall back to name matching when it is thin.
  if (hasInventory) {
    let onDisk = 0;
    let recorded = 0;
    for (const rel of new Set(derivedPaths(cat))) {
      if (!(await isRealFile(targetDir, rel))) continue;
      onDisk += 1;
      if (manifestFiles.has(rel)) recorded += 1;
    }
    if (onDisk >= 10 && recorded / onDisk < 0.6) {
      hasInventory = false;
      console.log(chalk.yellow(
        `  The install record only accounts for ${recorded} of the ${onDisk} Toh files I can see, so it is incomplete.\n` +
        '  I will match files by name instead, and save a copy of each one before removing it.\n'
      ));
    }
  }

  if (manifestBroken) {
    console.log(chalk.yellow('  The install record (.toh/manifest.json) is damaged — I will match files by name instead and leave anything unclear alone.\n'));
  }
  if (manifest && manifest.targetDir && resolve(manifest.targetDir) !== targetDir) {
    console.log(chalk.gray(
      `  Note: this project was installed at ${manifest.targetDir} and has been moved or copied since.\n` +
      `  I am only working on the folder you gave me (${targetDir}).\n`
    ));
  }
  if (!cat.ok && !hasInventory) {
    console.log(chalk.red(
      '  I could not read my own file list (the package looks incomplete) and there is no install record,\n' +
      '  so I cannot tell which files are mine. Nothing was changed.\n'
    ));
    return 1;
  }

  const ctx = {
    targetDir,
    cat,
    manifest,
    manifestFiles,
    hasInventory,
    includeUserWork,
    verbose,
    dirsCreated: Array.isArray(manifest?.dirsCreated) ? manifest.dirsCreated : [],
    backupDirName: '.toh-uninstall-backup'
  };

  const plan = await buildPlan(ctx);
  printPlan(plan, ctx);

  const interactive = !assumeYes && !dryRun && !!process.stdin.isTTY;
  // With nothing but the user's live work left, an interactive run must still
  // offer to remove it — otherwise those files are unremovable by this tool for
  // anyone who never discovers the --all flag.
  const canOfferLiveWork = interactive && plan.userWork.length === 0 && plan.liveWork.length > 0;
  const nothingToDo =
    plan.removals.length === 0 && plan.edits.length === 0 && plan.userWork.length === 0 &&
    !canOfferLiveWork;

  if (dryRun) {
    console.log(chalk.cyan('This was a preview (--dry-run). Nothing was deleted or changed.\n'));
    return 0;
  }
  if (nothingToDo) {
    console.log(chalk.green('There is nothing for me to remove. Nothing was changed.\n'));
    if (plan.liveWork.length > 0) {
      console.log(chalk.gray(
        `  Only your own plan and notes are left (${plural(plan.liveWork.length, 'file', 'files')}).\n` +
        `  To delete those too — a copy is saved first — run:  ${CMD_UNINSTALL} --all\n`
      ));
    }
    return 0;
  }

  // --- one confirmation (two when the user's own work is involved) ---------
  if (!assumeYes) {
    if (!process.stdin.isTTY) {
      console.log(chalk.yellow(
        'I need a yes before deleting anything, but nobody is here to answer.\n' +
        'Run it again with --yes to go ahead, or --dry-run to just look.\n'
      ));
      return 1;
    }
    console.log(chalk.bold.yellow('Nothing has been deleted yet.\n'));
    let go = false;
    let alsoWork = includeUserWork;
    const liveCount = plan.userWork.length || plan.liveWork.length;
    try {
      ({ go } = await inquirer.prompt([{
        type: 'confirm',
        name: 'go',
        message: 'Go ahead and remove Toh Framework from this folder?',
        default: false
      }]));
      if (go && liveCount > 0) {
        ({ alsoWork } = await inquirer.prompt([{
          type: 'confirm',
          name: 'alsoWork',
          message: `Also delete YOUR OWN plan and notes (${plural(liveCount, 'file', 'files')})? A copy is saved first, but this is your project's work.`,
          default: false
        }]));
      }
    } catch {
      console.log(chalk.yellow('\nI could not read your answer, so I stopped and changed nothing.\n'));
      return 1;
    }
    if (!go) {
      console.log(chalk.green('\nOK — I stopped and changed nothing.\n'));
      return 0;
    }
    if (alsoWork) {
      adoptUserWork(plan);
    } else if (plan.userWork.length > 0) {
      for (const item of plan.userWork) {
        plan.keeps.push({
          rel: item.rel,
          group: item.group,
          liveState: true,
          why: 'your own project notes — you chose to keep them'
        });
      }
      plan.userWork = [];
    }
  }

  const result = await applyPlan(plan, ctx);
  const manifestKept = await finalizeManifest(ctx, plan, result);
  await printReport(ctx, plan, result, manifestKept);

  return result.failed.length > 0 ? 1 : 0;
}

export default { uninstall };
